/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.FlowLayout;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.AlgorithmMethod;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

import model.entidades.*;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;

/**
 *
 * @author Admin-PC
 */
public class ViewConcreta extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Boolean pesquisaBooks;
    Boolean pesquisaAuthors;
    Boolean pesquisaPublishers;
    DefaultTableModel modelo;
    DefaultTableModel modelo2;

    String EscolhaAbaInserir;


    public ViewConcreta() {
        initComponents();
        pack();
        setVisible(true);
        modelo = (DefaultTableModel) this.tabela_abaPesquisa.getModel();
        modelo2 = (DefaultTableModel) this.tabela_abaAutor.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1 = new javax.swing.ButtonGroup();
        janelacomabas = new javax.swing.JTabbedPane();
        abaPesquisa = new javax.swing.JPanel();
        tituloPesquisa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_abaPesquisa = new javax.swing.JTable();
        caixadetexto_abaPesquisa = new javax.swing.JTextField();
        botaopesquisar_abaPesquisa = new javax.swing.JButton();
        checkboxAutores_abaPesquisa = new javax.swing.JCheckBox();
        Filtrodepesquisa_abaPesquisa = new javax.swing.JLabel();
        checkboxLivros_abaPesquisa = new javax.swing.JCheckBox();
        checkboxEditoras_abaPesquisa = new javax.swing.JCheckBox();
        botaoAjuda_abaPesquisa = new javax.swing.JButton();

        // abaInserir = new javax.swing.JPanel();
        // titulo_abaInserir = new javax.swing.JLabel();
        // caixadetexto_abaInserir = new javax.swing.JTextField();
        // botaopesquisar_abaInserir = new javax.swing.JButton();
        // Filtrodepesquisa_abaInserir = new javax.swing.JLabel();
        // checkboxLivros_abainserir = new javax.swing.JCheckBox();
        // checkboxAutores_abaInserir = new javax.swing.JCheckBox();
        // checkboxEditoras_abaInserir = new javax.swing.JCheckBox();
        // jScrollPane2 = new javax.swing.JScrollPane();
        // tabela_abaInserir = new javax.swing.JTable();
        // botaoinserir_abaInserir = new javax.swing.JButton();

        abaDeletar = new javax.swing.JPanel();
        titulo_abaDeletar = new javax.swing.JLabel();
        caixadetexto_abaDeletar = new javax.swing.JTextField();
        botaopesquisar_abaDeletar = new javax.swing.JButton();
        Filtrodepesquisa_abaDeletar = new javax.swing.JLabel();
        checkboxLivros_abaDeletar = new javax.swing.JCheckBox();
        checkboxAutores_abaDeletar = new javax.swing.JCheckBox();
        checkboxEditoras_abaDeletar = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_abaDeletar = new javax.swing.JTable();
        botaoDeletar_abaDeletar = new javax.swing.JButton();
        abaAlterar = new javax.swing.JPanel();
        titulo_abaAlterar = new javax.swing.JLabel();
        caixadetexto_abaAlterar = new javax.swing.JTextField();
        botaopesquisar_abaAlterar = new javax.swing.JButton();
        Filtrodepesquisa_abaAlterar = new javax.swing.JLabel();
        checkboxLivros_abaAlterar = new javax.swing.JCheckBox();
        checkboxAutores_abaAlterar = new javax.swing.JCheckBox();
        checkboxEditoras_abaAlterar = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela_abaAlterar = new javax.swing.JTable();
        botaoAlterar_abaAlterar = new javax.swing.JButton();

        // OBJETOS DA ABA INSERIR

        abaInserir = new javax.swing.JPanel();
        titulo_abaInserir = new javax.swing.JLabel();
        botaoAjuda_abaInserir = new javax.swing.JButton();
        radioButton_AutorAbaInserir = new javax.swing.JRadioButton();
        radioButton_LivrosAbaInserir = new javax.swing.JRadioButton();
        radioButton_EditorasAbaInserir = new javax.swing.JRadioButton();
        caixadetexto_abaInserirSobreNome = new javax.swing.JTextField();
        caixadetexto_abaInserirNome1 = new javax.swing.JTextField();
        labelNome_abaInserir = new javax.swing.JLabel();
        labelSobreNome_abaInserir = new javax.swing.JLabel();
        caixadetexto_abaInserirTitulo = new javax.swing.JTextField();
        caixadetexto_abaInserirISBN = new javax.swing.JTextField();
        caixadetexto_abaInserirEditora = new javax.swing.JTextField();
        caixadetexto_abaInserirNome5 = new javax.swing.JTextField();
        labelISBN_abaInserir = new javax.swing.JLabel();
        labelTitulo_abaInserir = new javax.swing.JLabel();
        labelpreco_abaInserir = new javax.swing.JLabel();
        labelNomeDaEditora_radiolivros_abaInserir = new javax.swing.JLabel();
        botaoAutor_abainserir = new javax.swing.JButton();
        labelAutores_abainserir = new javax.swing.JLabel();
        labelAutoresEscolhidos_abaInserir = new javax.swing.JLabel();
        labelNomeDaEditora_abaInserir = new javax.swing.JLabel();
        caixadetexto_NomeDaEditora_abaInserir = new javax.swing.JTextField();
        labelURL_abaInserir = new javax.swing.JLabel();
        caixadetexto_URL_abaInserir = new javax.swing.JTextField();
        labelQueMostraConfimacao_abaInserir = new javax.swing.JLabel();
        botaoinserir_abaInserir1 = new javax.swing.JButton();
        popUp = new JDialog();
        tabela_abaAutor = new javax.swing.JTable();
        botao_autor = new JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        janelacomabas.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));

        abaPesquisa.setBorder(new javax.swing.border.MatteBorder(null));

        tituloPesquisa.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        tituloPesquisa.setText("Pesquisas e Consultas");

        tabela_abaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nº Ordem", "Sobrenome do Autor", "Nome do Autor", "Título do livro", "ISBN", "Preço", "Nome da editora", "URL"
            }
        ));
        jScrollPane1.setViewportView(tabela_abaPesquisa);

        caixadetexto_abaPesquisa.setBackground(new java.awt.Color(204, 204, 204));
        caixadetexto_abaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadetexto_abaPesquisaActionPerformed(evt);
            }
        });

        botaopesquisar_abaPesquisa.setBackground(new java.awt.Color(204, 204, 204));
        botaopesquisar_abaPesquisa.setText("Pesquisar");

        checkboxAutores_abaPesquisa.setText("Autores");
        checkboxAutores_abaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxAutores_abaPesquisaActionPerformed(evt);
            }
        });

        Filtrodepesquisa_abaPesquisa.setText("Pesquisar em:");

        checkboxLivros_abaPesquisa.setText("Livros");
        checkboxLivros_abaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxLivros_abaPesquisaActionPerformed(evt);
            }
        });

        checkboxEditoras_abaPesquisa.setText("Editoras");
        checkboxEditoras_abaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxEditoras_abaPesquisaActionPerformed(evt);
            }
        });

        botaoAjuda_abaPesquisa.setBackground(new java.awt.Color(204, 204, 204));
        botaoAjuda_abaPesquisa.setFont(new java.awt.Font("Swis721 Blk BT", 0, 14)); // NOI18N
        botaoAjuda_abaPesquisa.setText("Ajuda?");
        botaoAjuda_abaPesquisa.setToolTipText("");

        javax.swing.GroupLayout abaPesquisaLayout = new javax.swing.GroupLayout(abaPesquisa);
        abaPesquisa.setLayout(abaPesquisaLayout);
        abaPesquisaLayout.setHorizontalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaPesquisaLayout.createSequentialGroup()
                        .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaPesquisaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Filtrodepesquisa_abaPesquisa)
                                .addGap(122, 122, 122)
                                .addComponent(checkboxLivros_abaPesquisa)
                                .addGap(122, 122, 122)
                                //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkboxAutores_abaPesquisa)
                                .addGap(122, 122, 122)
                                .addComponent(checkboxEditoras_abaPesquisa))
                            .addComponent(caixadetexto_abaPesquisa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaopesquisar_abaPesquisa))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaPesquisaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tituloPesquisa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAjuda_abaPesquisa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaPesquisaLayout.setVerticalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPesquisa)
                .addGap(4, 4, 4)
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixadetexto_abaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisar_abaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxAutores_abaPesquisa)
                    .addComponent(Filtrodepesquisa_abaPesquisa)
                    .addComponent(checkboxLivros_abaPesquisa)
                    .addComponent(checkboxEditoras_abaPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAjuda_abaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        janelacomabas.addTab("Pesquisa", abaPesquisa);

       
        janelacomabas.addTab("Inserir", abaInserir);

        abaDeletar.setBorder(new javax.swing.border.MatteBorder(null));

        titulo_abaDeletar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        titulo_abaDeletar.setText("Deletar dados existentes");

        caixadetexto_abaDeletar.setBackground(new java.awt.Color(204, 204, 204));
        caixadetexto_abaDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadetexto_abaDeletarActionPerformed(evt);
            }
        });

        botaopesquisar_abaDeletar.setBackground(new java.awt.Color(204, 204, 204));
        botaopesquisar_abaDeletar.setText("Pesquisar");

        Filtrodepesquisa_abaDeletar.setText("Pesquisar em:");

        checkboxLivros_abaDeletar.setText("Livros");
        checkboxLivros_abaDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxLivros_abaDeletarActionPerformed(evt);
            }
        });

        checkboxAutores_abaDeletar.setText("Autores");
        checkboxAutores_abaDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxAutores_abaDeletarActionPerformed(evt);
            }
        });

        checkboxEditoras_abaDeletar.setText("Editoras");
        checkboxEditoras_abaDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxEditoras_abaDeletarActionPerformed(evt);
            }
        });

        tabela_abaDeletar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabela_abaDeletar);

        botaoDeletar_abaDeletar.setBackground(new java.awt.Color(255, 51, 51));
        botaoDeletar_abaDeletar.setFont(new java.awt.Font("Swis721 Blk BT", 0, 18)); // NOI18N
        botaoDeletar_abaDeletar.setText("Deletar");
        botaoDeletar_abaDeletar.setToolTipText("");

        javax.swing.GroupLayout abaDeletarLayout = new javax.swing.GroupLayout(abaDeletar);
        abaDeletar.setLayout(abaDeletarLayout);
        abaDeletarLayout.setHorizontalGroup(
            abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaDeletarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaDeletarLayout.createSequentialGroup()
                        .addGroup(abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaDeletarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Filtrodepesquisa_abaDeletar)
                                .addGap(18, 18, 18)
                                .addComponent(checkboxLivros_abaDeletar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(checkboxAutores_abaDeletar)
                                .addGap(122, 122, 122)
                                .addComponent(checkboxEditoras_abaDeletar))
                            .addComponent(caixadetexto_abaDeletar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaopesquisar_abaDeletar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaDeletarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titulo_abaDeletar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaDeletarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoDeletar_abaDeletar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaDeletarLayout.setVerticalGroup(
            abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaDeletarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_abaDeletar)
                .addGap(4, 4, 4)
                .addGroup(abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixadetexto_abaDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisar_abaDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxAutores_abaDeletar)
                    .addComponent(Filtrodepesquisa_abaDeletar)
                    .addComponent(checkboxLivros_abaDeletar)
                    .addComponent(checkboxEditoras_abaDeletar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoDeletar_abaDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        janelacomabas.addTab("Deletar", abaDeletar);

        abaAlterar.setBorder(new javax.swing.border.MatteBorder(null));

        titulo_abaAlterar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        titulo_abaAlterar.setText("Alterar dados existentes");

        caixadetexto_abaAlterar.setBackground(new java.awt.Color(204, 204, 204));
        caixadetexto_abaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadetexto_abaAlterarActionPerformed(evt);
            }
        });

        botaopesquisar_abaAlterar.setBackground(new java.awt.Color(204, 204, 204));
        botaopesquisar_abaAlterar.setText("Pesquisar");

        Filtrodepesquisa_abaAlterar.setText("Pesquisar em:");

        checkboxLivros_abaAlterar.setText("Livros");
        checkboxLivros_abaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxLivros_abaAlterarActionPerformed(evt);
            }
        });

        checkboxAutores_abaAlterar.setText("Autores");
        checkboxAutores_abaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxAutores_abaAlterarActionPerformed(evt);
            }
        });

        checkboxEditoras_abaAlterar.setText("Editoras");
        checkboxEditoras_abaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxEditoras_abaAlterarActionPerformed(evt);
            }
        });

        tabela_abaAlterar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabela_abaAlterar);

        botaoAlterar_abaAlterar.setBackground(new java.awt.Color(51, 255, 204));
        botaoAlterar_abaAlterar.setFont(new java.awt.Font("Swis721 Blk BT", 0, 18)); // NOI18N
        botaoAlterar_abaAlterar.setText("Alterar");
        botaoAlterar_abaAlterar.setToolTipText("");

        javax.swing.GroupLayout abaAlterarLayout = new javax.swing.GroupLayout(abaAlterar);
        abaAlterar.setLayout(abaAlterarLayout);
        abaAlterarLayout.setHorizontalGroup(
            abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaAlterarLayout.createSequentialGroup()
                        .addGroup(abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaAlterarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Filtrodepesquisa_abaAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(checkboxLivros_abaAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(checkboxAutores_abaAlterar)
                                .addGap(122, 122, 122)
                                .addComponent(checkboxEditoras_abaAlterar))
                            .addComponent(caixadetexto_abaAlterar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaopesquisar_abaAlterar))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaAlterarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAlterar_abaAlterar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(abaAlterarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo_abaAlterar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaAlterarLayout.setVerticalGroup(
            abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_abaAlterar)
                .addGap(4, 4, 4)
                .addGroup(abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixadetexto_abaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisar_abaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxAutores_abaAlterar)
                    .addComponent(Filtrodepesquisa_abaAlterar)
                    .addComponent(checkboxLivros_abaAlterar)
                    .addComponent(checkboxEditoras_abaAlterar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAlterar_abaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        janelacomabas.addTab("Alterar", abaAlterar);
        
        abaInserir.setBorder(new javax.swing.border.MatteBorder(null));

        titulo_abaInserir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        titulo_abaInserir.setText("Inserir novos dados");

        botaoAjuda_abaInserir.setBackground(new java.awt.Color(204, 204, 204));
        botaoAjuda_abaInserir.setFont(new java.awt.Font("Swis721 Blk BT", 0, 18)); // NOI18N
        botaoAjuda_abaInserir.setText("Ajuda?");
        botaoAjuda_abaInserir.setToolTipText("");

        g1.add(radioButton_AutorAbaInserir);
        radioButton_AutorAbaInserir.setText("Autor");
        radioButton_AutorAbaInserir.setToolTipText("");

        g1.add(radioButton_LivrosAbaInserir);
        radioButton_LivrosAbaInserir.setText("Livros");

        g1.add(radioButton_EditorasAbaInserir);
        radioButton_EditorasAbaInserir.setText("Editoras");

        labelNome_abaInserir.setText("Primeiro nome: ");

        labelSobreNome_abaInserir.setText("Sobrenome:");

        caixadetexto_abaInserirNome5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadetexto_abaInserirNome5ActionPerformed(evt);
            }
        });

        labelISBN_abaInserir.setText("ISBN");

        labelTitulo_abaInserir.setText("Título do Livro: ");

        labelpreco_abaInserir.setText("Preço:");

        labelNomeDaEditora_radiolivros_abaInserir.setText("Nome da Editora:");
        labelNomeDaEditora_radiolivros_abaInserir.setToolTipText("");

        botaoAutor_abainserir.setText("Escolher Autor");
        botaoAutor_abainserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAutor_abainserirActionPerformed(evt);
            }
        });

        labelAutores_abainserir.setText("Autores:");

        labelAutoresEscolhidos_abaInserir.setText("");
        labelAutoresEscolhidos_abaInserir.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                labelAutoresEscolhidos_abaInserirComponentAdded(evt);
            }
        });

        labelNomeDaEditora_abaInserir.setText("Nome da Editora:");

        labelURL_abaInserir.setText("URL:");

        labelQueMostraConfimacao_abaInserir.setText("(label que vai ser pra mostrar a confirmação de inserção, apagar depois tbm)");

        tabela_abaAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nº Ordem", "Sobrenome do Autor", "Nome do autor"
            }
        ));

        botaoinserir_abaInserir1.setBackground(new java.awt.Color(153, 255, 153));
        botaoinserir_abaInserir1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 18)); // NOI18N
        botaoinserir_abaInserir1.setText("Inserir");
        botaoinserir_abaInserir1.setToolTipText("");

        javax.swing.GroupLayout abaInserirLayout = new javax.swing.GroupLayout(abaInserir);
        abaInserir.setLayout(abaInserirLayout);
        abaInserirLayout.setHorizontalGroup(
            abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirLayout.createSequentialGroup()
                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(abaInserirLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaInserirLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelAutoresEscolhidos_abaInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(abaInserirLayout.createSequentialGroup()
                                        .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(abaInserirLayout.createSequentialGroup()
                                                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(botaoAutor_abainserir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(labelAutores_abainserir))
                                                .addGap(18, 18, 18)
                                                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(abaInserirLayout.createSequentialGroup()
                                                        .addComponent(labelNomeDaEditora_radiolivros_abaInserir)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(caixadetexto_abaInserirEditora))
                                                    .addGroup(abaInserirLayout.createSequentialGroup()
                                                        .addComponent(labelTitulo_abaInserir)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(caixadetexto_abaInserirTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(21, 21, 21)
                                                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(labelpreco_abaInserir)
                                                    .addComponent(labelISBN_abaInserir))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(caixadetexto_abaInserirISBN)
                                                    .addComponent(caixadetexto_abaInserirNome5, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                                            .addGroup(abaInserirLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(labelNome_abaInserir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(caixadetexto_abaInserirNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelSobreNome_abaInserir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(caixadetexto_abaInserirSobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(2, 2, 2))))
                            .addComponent(radioButton_AutorAbaInserir)
                            .addComponent(radioButton_EditorasAbaInserir)
                            .addComponent(radioButton_LivrosAbaInserir)
                            .addGroup(abaInserirLayout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(titulo_abaInserir))
                            .addGroup(abaInserirLayout.createSequentialGroup()
                                .addComponent(botaoAjuda_abaInserir)
                                .addGap(18, 18, 18)
                                .addComponent(labelQueMostraConfimacao_abaInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoinserir_abaInserir1))))
                    .addGroup(abaInserirLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(labelNomeDaEditora_abaInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caixadetexto_NomeDaEditora_abaInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelURL_abaInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caixadetexto_URL_abaInserir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaInserirLayout.setVerticalGroup(
            abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titulo_abaInserir)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(radioButton_AutorAbaInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome_abaInserir)
                    .addComponent(caixadetexto_abaInserirNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSobreNome_abaInserir)
                    .addComponent(caixadetexto_abaInserirSobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(radioButton_LivrosAbaInserir)
                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaInserirLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixadetexto_abaInserirTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixadetexto_abaInserirISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelISBN_abaInserir)
                            .addComponent(labelTitulo_abaInserir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNomeDaEditora_radiolivros_abaInserir)
                            .addComponent(caixadetexto_abaInserirNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelpreco_abaInserir)
                            .addComponent(caixadetexto_abaInserirEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(abaInserirLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botaoAutor_abainserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelAutores_abainserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(labelAutoresEscolhidos_abaInserir)
                .addGap(29, 29, 29)
                .addComponent(radioButton_EditorasAbaInserir)
                .addGap(18, 18, 18)
                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeDaEditora_abaInserir)
                    .addComponent(caixadetexto_NomeDaEditora_abaInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelURL_abaInserir)
                    .addComponent(caixadetexto_URL_abaInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQueMostraConfimacao_abaInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoinserir_abaInserir1)
                    .addComponent(botaoAjuda_abaInserir))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        janelacomabas.addTab("Inserir", abaInserir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(janelacomabas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(janelacomabas)
                .addContainerGap())
        );

       

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // MÉTODOS GERADOS PELO NETBEANS
    private void caixadetexto_abaInserirNome5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetexto_abaInserirNome5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetexto_abaInserirNome5ActionPerformed

    private void botaoAutor_abainserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAutor_abainserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAutor_abainserirActionPerformed

    private void labelAutoresEscolhidos_abaInserirComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_labelAutoresEscolhidos_abaInserirComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAutoresEscolhidos_abaInserirComponentAdded

    private void caixadetexto_abaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetexto_abaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetexto_abaPesquisaActionPerformed

    private void checkboxAutores_abaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAutores_abaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxAutores_abaPesquisaActionPerformed

    private void checkboxLivros_abaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxLivros_abaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxLivros_abaPesquisaActionPerformed

    private void checkboxEditoras_abaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxEditoras_abaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxEditoras_abaPesquisaActionPerformed

    private void caixadetexto_abaInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetexto_abaInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetexto_abaInserirActionPerformed

    private void checkboxLivros_abainserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxLivros_abainserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxLivros_abainserirActionPerformed

    private void checkboxAutores_abaInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAutores_abaInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxAutores_abaInserirActionPerformed

    private void checkboxEditoras_abaInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxEditoras_abaInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxEditoras_abaInserirActionPerformed

    private void caixadetexto_abaDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetexto_abaDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetexto_abaDeletarActionPerformed

    private void checkboxLivros_abaDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxLivros_abaDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxLivros_abaDeletarActionPerformed

    private void checkboxAutores_abaDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAutores_abaDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxAutores_abaDeletarActionPerformed

    private void checkboxEditoras_abaDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxEditoras_abaDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxEditoras_abaDeletarActionPerformed

    private void caixadetexto_abaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetexto_abaAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetexto_abaAlterarActionPerformed

    private void checkboxLivros_abaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxLivros_abaAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxLivros_abaAlterarActionPerformed

    private void checkboxAutores_abaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAutores_abaAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxAutores_abaAlterarActionPerformed

    private void checkboxEditoras_abaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxEditoras_abaAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxEditoras_abaAlterarActionPerformed

    // MÉTODOS JANELA ATUALIZAR

    public void realizaAtt(ActionListener al){
        this.botaoAlterar_abaAlterar.addActionListener(al);
    }

    // MÉTODOS JANELA PESQUISA

    public void attAutor(ActionListener al){
        this.botao_autor.addActionListener(al);
    }

    public void realizarPesquisa(ActionListener al){
        this.botaopesquisar_abaPesquisa.addActionListener(al);
    }

    public void habilita(){
        this.caixadetexto_abaPesquisa.setVisible(false);
    }
   
    public void informacoes(ActionListener al){
        this.botaoAjuda_abaPesquisa.addActionListener(al);
    }

    public String pesquisa(){
        int value;
        value = this.tabela_abaAutor.getSelectedRow();

        String texto = this.tabela_abaAutor.getValueAt(value, 1).toString() + " " + this.tabela_abaAutor.getValueAt(value, 2).toString() + " / ";
        return texto;
    }

    public void attTextoAutor(String texto){
        labelAutoresEscolhidos_abaInserir.setText(labelAutoresEscolhidos_abaInserir.getText() + " " + texto);
        
    }
    
    public void setOpcao(){

        this.pesquisaAuthors = checkboxAutores_abaPesquisa.isSelected();
        this.pesquisaBooks = checkboxLivros_abaPesquisa.isSelected();
        this.pesquisaPublishers = checkboxEditoras_abaPesquisa.isSelected();

    }

    public void popUp(){
        
        // JFrame table = new JFrame();
        // table.setSize(300, 300);
        // table.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

 
        popUp.setSize(500, 500);
        popUp.setLayout(new FlowLayout());
        popUp.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        
        // JPanel panel = new JPanel();
        JScrollPane scroll = new JScrollPane(tabela_abaAutor);


        botao_autor.setText("Adicionar");


        
        tabela_abaAutor.setSize(350, 350);


        // panel.add(tabela_abaAutor);
        // panel.setSize(480, 380);
        popUp.add(scroll);
        // popUp.add(tabela_abaAutor);
        popUp.add(botao_autor);
        popUp.setTitle("Selecione os autores do livro");

        // table.setVisible(true);

        popUp.setVisible(true); 

        // table.add(tabela_abaAutor);
        // table.add(botao_autor);
        // table.add(jScrollPane1);
        
    }

    public void addAutor(ActionListener al){
        this.botaoAutor_abainserir.addActionListener(al);
    }

    public void atualizaAutores(int contador, Autores autor){

        String[] infos = {(Integer.toString(contador)), autor.getName(), autor.getFname()};

        modelo2.addRow(infos);
        this.tabela_abaAutor.getTableHeader().resizeAndRepaint();
    }

    public Boolean getOpcaoAutorAbaInserir(){

       return radioButton_AutorAbaInserir.isSelected();
    }

    public Boolean getOpcaoEditoraAbaInserir(){

        return radioButton_EditorasAbaInserir.isSelected();
    }
    
    public Boolean getOpcaoLivroAbarInserir(){

        return radioButton_LivrosAbaInserir.isSelected();
    }
     
    public Boolean getOpcaoLivro(){
        return this.pesquisaBooks;
    }

    public Boolean getOpcaoAutor(){
        return this.pesquisaAuthors;
    }

    public Boolean getOpcaoEditora(){
        return this.pesquisaPublishers;
    }

    public String getTexto(){
        return this.caixadetexto_abaPesquisa.getText();
    }

    public void limpaTabela(){
        modelo.setRowCount(0);
    }

    public void atualizaTabelaAutor(int contador, Autores autor){

        String[] infos = {(Integer.toString(contador)), autor.getName(), autor.getFname()};

        modelo.addRow(infos);
        this.tabela_abaPesquisa.getTableHeader().resizeAndRepaint();
    }

    public void atualizaTabelaLivro(int contador, Livros livro){
        
        String[] infos = {(Integer.toString(contador)), "", "", livro.getTitle(), livro.getIsbn(), Float.toString(livro.getPrice())};

        modelo.addRow(infos);
        this.tabela_abaPesquisa.getTableHeader().resizeAndRepaint();
    }

    public void atualizaTabelaEditora(int contador, Editoras editora){
        
        String[] infos = {(Integer.toString(contador)), "", "", "", "", "", editora.getName(), editora.getUrl()};

        modelo.addRow(infos);
        this.tabela_abaPesquisa.getTableHeader().resizeAndRepaint();
    }

    public void atualizaTabelaRelGeral(int contador, RelTudo valor){

       
        String[] infos = {(Integer.toString(contador)), valor.getNomeAutor().getName(),valor.getSobrenome().getFname(), valor.getTitulo().getTitle(), valor.getIsbn().getIsbn(), Float.toString(valor.getPreco().getPrice()), valor.getNomeEditora().getName(), valor.getUrl().getUrl()};


        modelo.addRow(infos);
        this.tabela_abaPesquisa.getTableHeader().resizeAndRepaint();
    }

    public void atualizaRelLivroAutor(int contador, RelLivrosAutores dados){

        String[] infos = {(Integer.toString(contador)),  dados.getSobrenome().getName(), dados.getNome().getFname(), dados.getTitulo().getTitle(), dados.getIsbn().getIsbn(), Float.toString(dados.getPreco().getPrice())};

        modelo.addRow(infos);
        this.tabela_abaPesquisa.getTableHeader().resizeAndRepaint();
    }

    public void mensagemErro(){
        JOptionPane.showMessageDialog(null, "TESTE", "Erro ", JOptionPane.INFORMATION_MESSAGE);
    }

    public void mensagemAjudaPesquisa(){

        String[] infos = {"Nas checkboxs escolha os campos que deseja pesquisar.", "Autores: Pesquisas feitas no sobrenome", "Livros: Pesquisas feitas pelo título.", "Editoras: Pesquisas feitas pelo nome."};
        JOptionPane.showMessageDialog(null, infos, "Como realizar as pesquisas:", JOptionPane.INFORMATION_MESSAGE);
    }

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConcreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConcreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConcreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConcreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewConcreta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1;
    private javax.swing.JLabel Filtrodepesquisa_abaAlterar;
    private javax.swing.JLabel Filtrodepesquisa_abaDeletar;
    private javax.swing.JLabel Filtrodepesquisa_abaInserir;
    private javax.swing.JLabel Filtrodepesquisa_abaPesquisa;
    private javax.swing.JPanel abaAlterar;
    private javax.swing.JPanel abaDeletar;
    private javax.swing.JPanel abaInserir;
    private javax.swing.JPanel abaPesquisa;
    private javax.swing.JButton botaoAlterar_abaAlterar;
    private javax.swing.JButton botaoDeletar_abaDeletar;
    private javax.swing.JButton botaoinserir_abaInserir;
    private javax.swing.JButton botaopesquisar_abaAlterar;
    private javax.swing.JButton botaopesquisar_abaDeletar;
    private javax.swing.JButton botaopesquisar_abaInserir;
    private javax.swing.JButton botaopesquisar_abaPesquisa;
    private javax.swing.JButton botaoAjuda_abaPesquisa;
    private javax.swing.JTextField caixadetexto_abaAlterar;
    private javax.swing.JTextField caixadetexto_abaDeletar;
    private javax.swing.JTextField caixadetexto_abaInserir;
    private javax.swing.JTextField caixadetexto_abaPesquisa;
    private javax.swing.JCheckBox checkboxAutores_abaAlterar;
    private javax.swing.JCheckBox checkboxAutores_abaDeletar;
    private javax.swing.JCheckBox checkboxAutores_abaInserir;
    private javax.swing.JCheckBox checkboxAutores_abaPesquisa;
    private javax.swing.JCheckBox checkboxEditoras_abaAlterar;
    private javax.swing.JCheckBox checkboxEditoras_abaDeletar;
    private javax.swing.JCheckBox checkboxEditoras_abaInserir;
    private javax.swing.JCheckBox checkboxEditoras_abaPesquisa;
    private javax.swing.JCheckBox checkboxLivros_abaAlterar;
    private javax.swing.JCheckBox checkboxLivros_abaDeletar;
    private javax.swing.JCheckBox checkboxLivros_abaPesquisa;
    private javax.swing.JCheckBox checkboxLivros_abainserir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane janelacomabas;
    private javax.swing.JTable tabela_abaAlterar;
    private javax.swing.JTable tabela_abaDeletar;
    private javax.swing.JTable tabela_abaInserir;
    private javax.swing.JTable tabela_abaPesquisa;
    private javax.swing.JLabel tituloPesquisa;
    private javax.swing.JLabel titulo_abaAlterar;
    private javax.swing.JLabel titulo_abaDeletar;
    private javax.swing.JLabel titulo_abaInserir;

    // VARIAVEIS ABA INSERIR


    private javax.swing.JButton botaoinserir_abaInserir1;
    private javax.swing.JButton botaoAutor_abainserir;
    private javax.swing.JButton botaoAjuda_abaInserir;

     private JDialog popUp;

    private javax.swing.JTextField caixadetexto_NomeDaEditora_abaInserir;
    private javax.swing.JTextField caixadetexto_URL_abaInserir;

    private javax.swing.JTextField caixadetexto_abaInserirEditora;
    private javax.swing.JTextField caixadetexto_abaInserirISBN;
    private javax.swing.JTextField caixadetexto_abaInserirNome1;
    private javax.swing.JTextField caixadetexto_abaInserirNome5;
    private javax.swing.JTextField caixadetexto_abaInserirSobreNome;
    private javax.swing.JTextField caixadetexto_abaInserirTitulo;

    private javax.swing.JLabel labelAutoresEscolhidos_abaInserir;
    private javax.swing.JLabel labelAutores_abainserir;
    private javax.swing.JLabel labelISBN_abaInserir;
    private javax.swing.JLabel labelNomeDaEditora_abaInserir;
    private javax.swing.JLabel labelNomeDaEditora_radiolivros_abaInserir;
    private javax.swing.JLabel labelNome_abaInserir;
    private javax.swing.JLabel labelQueMostraConfimacao_abaInserir;
    private javax.swing.JLabel labelSobreNome_abaInserir;
    private javax.swing.JLabel labelTitulo_abaInserir;
    private javax.swing.JLabel labelURL_abaInserir;
    private javax.swing.JLabel labelpreco_abaInserir;
    private javax.swing.JRadioButton radioButton_AutorAbaInserir;
    private javax.swing.JRadioButton radioButton_EditorasAbaInserir;
    private javax.swing.JRadioButton radioButton_LivrosAbaInserir;

    private JTable tabela_abaAutor ;
    private JButton botao_autor;


    // End of variables declaration//GEN-END:variables
}
