/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.AlgorithmMethod;
import java.util.List;
import javax.swing.JOptionPane;

import model.entidades.*;
import view.tables.RelTotalTableModel;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;

/**
 *
 * @author Admin-PC
 */
public class ViewConcreta extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Boolean pesquisaBooks;
    Boolean pesquisaAuthors;
    Boolean pesquisaPublishers;
    DefaultTableModel modelo;

    public ViewConcreta() {
        initComponents();
        pack();
        setVisible(true);
        modelo = (DefaultTableModel) this.tabela_abaPesquisa.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelacomabas = new javax.swing.JTabbedPane();
        abaPesquisa = new javax.swing.JPanel();
        tituloPesquisa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_abaPesquisa = new javax.swing.JTable();
        caixadetexto_abaPesquisa = new javax.swing.JTextField();
        botaopesquisar_abaPesquisa = new javax.swing.JButton();
        checkboxAutores_abaPesquisa = new javax.swing.JCheckBox();
        Filtrodepesquisa_abaPesquisa = new javax.swing.JLabel();
        checkboxLivros_abaPesquisa = new javax.swing.JCheckBox();
        checkboxEditoras_abaPesquisa = new javax.swing.JCheckBox();
        botaoAjuda_abaPesquisa = new javax.swing.JButton();
        abaInserir = new javax.swing.JPanel();
        titulo_abaInserir = new javax.swing.JLabel();
        caixadetexto_abaInserir = new javax.swing.JTextField();
        botaopesquisar_abaInserir = new javax.swing.JButton();
        Filtrodepesquisa_abaInserir = new javax.swing.JLabel();
        checkboxLivros_abainserir = new javax.swing.JCheckBox();
        checkboxAutores_abaInserir = new javax.swing.JCheckBox();
        checkboxEditoras_abaInserir = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_abaInserir = new javax.swing.JTable();
        botaoinserir_abaInserir = new javax.swing.JButton();
        abaDeletar = new javax.swing.JPanel();
        titulo_abaDeletar = new javax.swing.JLabel();
        caixadetexto_abaDeletar = new javax.swing.JTextField();
        botaopesquisar_abaDeletar = new javax.swing.JButton();
        Filtrodepesquisa_abaDeletar = new javax.swing.JLabel();
        checkboxLivros_abaDeletar = new javax.swing.JCheckBox();
        checkboxAutores_abaDeletar = new javax.swing.JCheckBox();
        checkboxEditoras_abaDeletar = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_abaDeletar = new javax.swing.JTable();
        botaoDeletar_abaDeletar = new javax.swing.JButton();
        abaAlterar = new javax.swing.JPanel();
        titulo_abaAlterar = new javax.swing.JLabel();
        caixadetexto_abaAlterar = new javax.swing.JTextField();
        botaopesquisar_abaAlterar = new javax.swing.JButton();
        Filtrodepesquisa_abaAlterar = new javax.swing.JLabel();
        checkboxLivros_abaAlterar = new javax.swing.JCheckBox();
        checkboxAutores_abaAlterar = new javax.swing.JCheckBox();
        checkboxEditoras_abaAlterar = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela_abaAlterar = new javax.swing.JTable();
        botaoAlterar_abaAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        janelacomabas.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));

        abaPesquisa.setBorder(new javax.swing.border.MatteBorder(null));

        tituloPesquisa.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        tituloPesquisa.setText("Pesquisas e Consultas");

        tabela_abaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nº Ordem", "Sobrenome do Autor", "Nome do Autor", "Título do livro", "ISBN", "Preço", "Nome da editora", "URL"
            }
        ));
        jScrollPane1.setViewportView(tabela_abaPesquisa);

        caixadetexto_abaPesquisa.setBackground(new java.awt.Color(204, 204, 204));
        caixadetexto_abaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadetexto_abaPesquisaActionPerformed(evt);
            }
        });

        botaopesquisar_abaPesquisa.setBackground(new java.awt.Color(204, 204, 204));
        botaopesquisar_abaPesquisa.setText("Pesquisar");

        checkboxAutores_abaPesquisa.setText("Autores");
        checkboxAutores_abaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxAutores_abaPesquisaActionPerformed(evt);
            }
        });

        Filtrodepesquisa_abaPesquisa.setText("Pesquisar em:");

        checkboxLivros_abaPesquisa.setText("Livros");
        checkboxLivros_abaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxLivros_abaPesquisaActionPerformed(evt);
            }
        });

        checkboxEditoras_abaPesquisa.setText("Editoras");
        checkboxEditoras_abaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxEditoras_abaPesquisaActionPerformed(evt);
            }
        });

        botaoAjuda_abaPesquisa.setBackground(new java.awt.Color(204, 204, 204));
        botaoAjuda_abaPesquisa.setFont(new java.awt.Font("Swis721 Blk BT", 0, 14)); // NOI18N
        botaoAjuda_abaPesquisa.setText("Ajuda?");
        botaoAjuda_abaPesquisa.setToolTipText("");

        javax.swing.GroupLayout abaPesquisaLayout = new javax.swing.GroupLayout(abaPesquisa);
        abaPesquisa.setLayout(abaPesquisaLayout);
        abaPesquisaLayout.setHorizontalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaPesquisaLayout.createSequentialGroup()
                        .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaPesquisaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Filtrodepesquisa_abaPesquisa)
                                .addGap(122, 122, 122)
                                .addComponent(checkboxLivros_abaPesquisa)
                                .addGap(122, 122, 122)
                                //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkboxAutores_abaPesquisa)
                                .addGap(122, 122, 122)
                                .addComponent(checkboxEditoras_abaPesquisa))
                            .addComponent(caixadetexto_abaPesquisa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaopesquisar_abaPesquisa))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaPesquisaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tituloPesquisa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAjuda_abaPesquisa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaPesquisaLayout.setVerticalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPesquisa)
                .addGap(4, 4, 4)
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixadetexto_abaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisar_abaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxAutores_abaPesquisa)
                    .addComponent(Filtrodepesquisa_abaPesquisa)
                    .addComponent(checkboxLivros_abaPesquisa)
                    .addComponent(checkboxEditoras_abaPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAjuda_abaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        janelacomabas.addTab("Pesquisa", abaPesquisa);

        abaInserir.setBorder(new javax.swing.border.MatteBorder(null));

        titulo_abaInserir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        titulo_abaInserir.setText("Inserir novos dados");

        caixadetexto_abaInserir.setBackground(new java.awt.Color(204, 204, 204));
        caixadetexto_abaInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadetexto_abaInserirActionPerformed(evt);
            }
        });

        botaopesquisar_abaInserir.setBackground(new java.awt.Color(204, 204, 204));
        botaopesquisar_abaInserir.setText("Pesquisar");

        Filtrodepesquisa_abaInserir.setText("Pesquisar em:");

        checkboxLivros_abainserir.setText("Livros");
        checkboxLivros_abainserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxLivros_abainserirActionPerformed(evt);
            }
        });

        checkboxAutores_abaInserir.setText("Autores");
        checkboxAutores_abaInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxAutores_abaInserirActionPerformed(evt);
            }
        });

        checkboxEditoras_abaInserir.setText("Editoras");
        checkboxEditoras_abaInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxEditoras_abaInserirActionPerformed(evt);
            }
        });

        tabela_abaInserir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabela_abaInserir);

        botaoinserir_abaInserir.setBackground(new java.awt.Color(153, 255, 153));
        botaoinserir_abaInserir.setFont(new java.awt.Font("Swis721 Blk BT", 0, 18)); // NOI18N
        botaoinserir_abaInserir.setText("Inserir");
        botaoinserir_abaInserir.setToolTipText("");

        javax.swing.GroupLayout abaInserirLayout = new javax.swing.GroupLayout(abaInserir);
        abaInserir.setLayout(abaInserirLayout);
        abaInserirLayout.setHorizontalGroup(
            abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaInserirLayout.createSequentialGroup()
                        .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaInserirLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Filtrodepesquisa_abaInserir)
                                .addGap(18, 18, 18)
                                .addComponent(checkboxLivros_abainserir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(checkboxAutores_abaInserir)
                                .addGap(122, 122, 122)
                                .addComponent(checkboxEditoras_abaInserir))
                            .addComponent(caixadetexto_abaInserir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaopesquisar_abaInserir))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaInserirLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titulo_abaInserir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(abaInserirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoinserir_abaInserir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaInserirLayout.setVerticalGroup(
            abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_abaInserir)
                .addGap(4, 4, 4)
                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixadetexto_abaInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisar_abaInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxAutores_abaInserir)
                    .addComponent(Filtrodepesquisa_abaInserir)
                    .addComponent(checkboxLivros_abainserir)
                    .addComponent(checkboxEditoras_abaInserir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoinserir_abaInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        janelacomabas.addTab("Inserir", abaInserir);

        abaDeletar.setBorder(new javax.swing.border.MatteBorder(null));

        titulo_abaDeletar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        titulo_abaDeletar.setText("Deletar dados existentes");

        caixadetexto_abaDeletar.setBackground(new java.awt.Color(204, 204, 204));
        caixadetexto_abaDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadetexto_abaDeletarActionPerformed(evt);
            }
        });

        botaopesquisar_abaDeletar.setBackground(new java.awt.Color(204, 204, 204));
        botaopesquisar_abaDeletar.setText("Pesquisar");

        Filtrodepesquisa_abaDeletar.setText("Pesquisar em:");

        checkboxLivros_abaDeletar.setText("Livros");
        checkboxLivros_abaDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxLivros_abaDeletarActionPerformed(evt);
            }
        });

        checkboxAutores_abaDeletar.setText("Autores");
        checkboxAutores_abaDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxAutores_abaDeletarActionPerformed(evt);
            }
        });

        checkboxEditoras_abaDeletar.setText("Editoras");
        checkboxEditoras_abaDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxEditoras_abaDeletarActionPerformed(evt);
            }
        });

        tabela_abaDeletar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabela_abaDeletar);

        botaoDeletar_abaDeletar.setBackground(new java.awt.Color(255, 51, 51));
        botaoDeletar_abaDeletar.setFont(new java.awt.Font("Swis721 Blk BT", 0, 18)); // NOI18N
        botaoDeletar_abaDeletar.setText("Deletar");
        botaoDeletar_abaDeletar.setToolTipText("");

        javax.swing.GroupLayout abaDeletarLayout = new javax.swing.GroupLayout(abaDeletar);
        abaDeletar.setLayout(abaDeletarLayout);
        abaDeletarLayout.setHorizontalGroup(
            abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaDeletarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaDeletarLayout.createSequentialGroup()
                        .addGroup(abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaDeletarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Filtrodepesquisa_abaDeletar)
                                .addGap(18, 18, 18)
                                .addComponent(checkboxLivros_abaDeletar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(checkboxAutores_abaDeletar)
                                .addGap(122, 122, 122)
                                .addComponent(checkboxEditoras_abaDeletar))
                            .addComponent(caixadetexto_abaDeletar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaopesquisar_abaDeletar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaDeletarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titulo_abaDeletar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaDeletarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoDeletar_abaDeletar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaDeletarLayout.setVerticalGroup(
            abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaDeletarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_abaDeletar)
                .addGap(4, 4, 4)
                .addGroup(abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixadetexto_abaDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisar_abaDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxAutores_abaDeletar)
                    .addComponent(Filtrodepesquisa_abaDeletar)
                    .addComponent(checkboxLivros_abaDeletar)
                    .addComponent(checkboxEditoras_abaDeletar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoDeletar_abaDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        janelacomabas.addTab("Deletar", abaDeletar);

        abaAlterar.setBorder(new javax.swing.border.MatteBorder(null));

        titulo_abaAlterar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        titulo_abaAlterar.setText("Alterar dados existentes");

        caixadetexto_abaAlterar.setBackground(new java.awt.Color(204, 204, 204));
        caixadetexto_abaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadetexto_abaAlterarActionPerformed(evt);
            }
        });

        botaopesquisar_abaAlterar.setBackground(new java.awt.Color(204, 204, 204));
        botaopesquisar_abaAlterar.setText("Pesquisar");

        Filtrodepesquisa_abaAlterar.setText("Pesquisar em:");

        checkboxLivros_abaAlterar.setText("Livros");
        checkboxLivros_abaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxLivros_abaAlterarActionPerformed(evt);
            }
        });

        checkboxAutores_abaAlterar.setText("Autores");
        checkboxAutores_abaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxAutores_abaAlterarActionPerformed(evt);
            }
        });

        checkboxEditoras_abaAlterar.setText("Editoras");
        checkboxEditoras_abaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxEditoras_abaAlterarActionPerformed(evt);
            }
        });

        tabela_abaAlterar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabela_abaAlterar);

        botaoAlterar_abaAlterar.setBackground(new java.awt.Color(51, 255, 204));
        botaoAlterar_abaAlterar.setFont(new java.awt.Font("Swis721 Blk BT", 0, 18)); // NOI18N
        botaoAlterar_abaAlterar.setText("Alterar");
        botaoAlterar_abaAlterar.setToolTipText("");

        javax.swing.GroupLayout abaAlterarLayout = new javax.swing.GroupLayout(abaAlterar);
        abaAlterar.setLayout(abaAlterarLayout);
        abaAlterarLayout.setHorizontalGroup(
            abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaAlterarLayout.createSequentialGroup()
                        .addGroup(abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaAlterarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Filtrodepesquisa_abaAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(checkboxLivros_abaAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(checkboxAutores_abaAlterar)
                                .addGap(122, 122, 122)
                                .addComponent(checkboxEditoras_abaAlterar))
                            .addComponent(caixadetexto_abaAlterar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaopesquisar_abaAlterar))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaAlterarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAlterar_abaAlterar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(abaAlterarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo_abaAlterar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaAlterarLayout.setVerticalGroup(
            abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_abaAlterar)
                .addGap(4, 4, 4)
                .addGroup(abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixadetexto_abaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisar_abaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxAutores_abaAlterar)
                    .addComponent(Filtrodepesquisa_abaAlterar)
                    .addComponent(checkboxLivros_abaAlterar)
                    .addComponent(checkboxEditoras_abaAlterar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAlterar_abaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        janelacomabas.addTab("Alterar", abaAlterar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(janelacomabas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(janelacomabas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // MÉTODOS GERADOS PELO NETBEANS

    private void caixadetexto_abaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetexto_abaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetexto_abaPesquisaActionPerformed

    private void checkboxAutores_abaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAutores_abaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxAutores_abaPesquisaActionPerformed

    private void checkboxLivros_abaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxLivros_abaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxLivros_abaPesquisaActionPerformed

    private void checkboxEditoras_abaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxEditoras_abaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxEditoras_abaPesquisaActionPerformed

    private void caixadetexto_abaInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetexto_abaInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetexto_abaInserirActionPerformed

    private void checkboxLivros_abainserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxLivros_abainserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxLivros_abainserirActionPerformed

    private void checkboxAutores_abaInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAutores_abaInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxAutores_abaInserirActionPerformed

    private void checkboxEditoras_abaInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxEditoras_abaInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxEditoras_abaInserirActionPerformed

    private void caixadetexto_abaDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetexto_abaDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetexto_abaDeletarActionPerformed

    private void checkboxLivros_abaDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxLivros_abaDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxLivros_abaDeletarActionPerformed

    private void checkboxAutores_abaDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAutores_abaDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxAutores_abaDeletarActionPerformed

    private void checkboxEditoras_abaDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxEditoras_abaDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxEditoras_abaDeletarActionPerformed

    private void caixadetexto_abaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetexto_abaAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetexto_abaAlterarActionPerformed

    private void checkboxLivros_abaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxLivros_abaAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxLivros_abaAlterarActionPerformed

    private void checkboxAutores_abaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAutores_abaAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxAutores_abaAlterarActionPerformed

    private void checkboxEditoras_abaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxEditoras_abaAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxEditoras_abaAlterarActionPerformed

    // MÉTODOS CRIADOS

    public void realizarPesquisa(ActionListener al){
        this.botaopesquisar_abaPesquisa.addActionListener(al);
    }

    public void informacoes(ActionListener al){
        this.botaoAjuda_abaPesquisa.addActionListener(al);
    }

    public void setOpcao(){

        this.pesquisaAuthors = checkboxAutores_abaPesquisa.isSelected();
        this.pesquisaBooks = checkboxLivros_abaPesquisa.isSelected();
        this.pesquisaPublishers = checkboxEditoras_abaPesquisa.isSelected();

    }

    public Boolean getOpcaoLivro(){
        return this.pesquisaBooks;
    }

    public Boolean getOpcaoAutor(){
        return this.pesquisaAuthors;
    }

    public Boolean getOpcaoEditora(){
        return this.pesquisaPublishers;
    }

    public String getTexto(){
        return this.caixadetexto_abaPesquisa.getText();
    }

    public void limpaTabela(){
        modelo.setRowCount(0);
    }

    public void atualizaTabelaAutor(int contador, Autores autor){

        String[] infos = {(Integer.toString(contador)), autor.getName(), autor.getFname()};

        modelo.addRow(infos);
        this.tabela_abaPesquisa.getTableHeader().resizeAndRepaint();
    }

    public void atualizaTabelaLivro(int contador, Livros livro){
        
        String[] infos = {(Integer.toString(contador)), "", "", livro.getTitle(), livro.getIsbn(), Float.toString(livro.getPrice())};

        modelo.addRow(infos);
        this.tabela_abaPesquisa.getTableHeader().resizeAndRepaint();
    }

    public void atualizaTabelaEditora(int contador, Editoras editora){
        
        String[] infos = {(Integer.toString(contador)), "", "", "", "", "", editora.getName(), editora.getUrl()};

        modelo.addRow(infos);
        this.tabela_abaPesquisa.getTableHeader().resizeAndRepaint();
    }

    public void atualizaTabelaRelGeral(int contador, RelTudo valor){

       
        String[] infos = {(Integer.toString(contador)), valor.getNomeAutor().getName(),valor.getSobrenome().getFname(), valor.getTitulo().getTitle(), valor.getIsbn().getIsbn(), Float.toString(valor.getPreco().getPrice()), valor.getNomeEditora().getName(), valor.getUrl().getUrl()};


        modelo.addRow(infos);
        this.tabela_abaPesquisa.getTableHeader().resizeAndRepaint();
    }

    public void atualizaRelLivroAutor(int contador, RelLivrosAutores dados){

        String[] infos = {(Integer.toString(contador)),  dados.getSobrenome().getName(), dados.getNome().getFname(), dados.getTitulo().getTitle(), dados.getIsbn().getIsbn(), Float.toString(dados.getPreco().getPrice())};

        modelo.addRow(infos);
        this.tabela_abaPesquisa.getTableHeader().resizeAndRepaint();
    }

    public void mensagemErro(){
        JOptionPane.showMessageDialog(null, "TESTE", "Erro ", JOptionPane.INFORMATION_MESSAGE);
    }

    public void mensagemAjudaPesquisa(){

        String[] infos = {"Nas checkboxs escolha os campos que deseja pesquisar.", "Autores: Pesquisas feitas no sobrenome", "Livros: Pesquisas feitas pelo título.", "Editoras: Pesquisas feitas pelo nome."};
        JOptionPane.showMessageDialog(null, infos, "Como realizar as pesquisas:", JOptionPane.INFORMATION_MESSAGE);
    }

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConcreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConcreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConcreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConcreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewConcreta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Filtrodepesquisa_abaAlterar;
    private javax.swing.JLabel Filtrodepesquisa_abaDeletar;
    private javax.swing.JLabel Filtrodepesquisa_abaInserir;
    private javax.swing.JLabel Filtrodepesquisa_abaPesquisa;
    private javax.swing.JPanel abaAlterar;
    private javax.swing.JPanel abaDeletar;
    private javax.swing.JPanel abaInserir;
    private javax.swing.JPanel abaPesquisa;
    private javax.swing.JButton botaoAlterar_abaAlterar;
    private javax.swing.JButton botaoDeletar_abaDeletar;
    private javax.swing.JButton botaoinserir_abaInserir;
    private javax.swing.JButton botaopesquisar_abaAlterar;
    private javax.swing.JButton botaopesquisar_abaDeletar;
    private javax.swing.JButton botaopesquisar_abaInserir;
    private javax.swing.JButton botaopesquisar_abaPesquisa;
    private javax.swing.JButton botaoAjuda_abaPesquisa;
    private javax.swing.JTextField caixadetexto_abaAlterar;
    private javax.swing.JTextField caixadetexto_abaDeletar;
    private javax.swing.JTextField caixadetexto_abaInserir;
    private javax.swing.JTextField caixadetexto_abaPesquisa;
    private javax.swing.JCheckBox checkboxAutores_abaAlterar;
    private javax.swing.JCheckBox checkboxAutores_abaDeletar;
    private javax.swing.JCheckBox checkboxAutores_abaInserir;
    private javax.swing.JCheckBox checkboxAutores_abaPesquisa;
    private javax.swing.JCheckBox checkboxEditoras_abaAlterar;
    private javax.swing.JCheckBox checkboxEditoras_abaDeletar;
    private javax.swing.JCheckBox checkboxEditoras_abaInserir;
    private javax.swing.JCheckBox checkboxEditoras_abaPesquisa;
    private javax.swing.JCheckBox checkboxLivros_abaAlterar;
    private javax.swing.JCheckBox checkboxLivros_abaDeletar;
    private javax.swing.JCheckBox checkboxLivros_abaPesquisa;
    private javax.swing.JCheckBox checkboxLivros_abainserir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane janelacomabas;
    private javax.swing.JTable tabela_abaAlterar;
    private javax.swing.JTable tabela_abaDeletar;
    private javax.swing.JTable tabela_abaInserir;
    private javax.swing.JTable tabela_abaPesquisa;
    private javax.swing.JLabel tituloPesquisa;
    private javax.swing.JLabel titulo_abaAlterar;
    private javax.swing.JLabel titulo_abaDeletar;
    private javax.swing.JLabel titulo_abaInserir;
    // End of variables declaration//GEN-END:variables
}
